### ISSUE TITLE
DAPLINK firmware versions

### ISSUE THREAD

**Issue by ScarsFun** [WeActStudio/WeActStudio.MiniDebugger#3]
Which is difference in DAPLINK firmwares, "if" and "bl"?
Thanks.

**Comment by FT9R** [comment]
> Which is difference in DAPLINK firmwares, "if" and "bl"? Thanks.

'if' stands for interface. And 'bl' stands for bootloader.
Both have to be burned to the MCU, but each in a separate memory location

**Comment by ScarsFun** [comment]
Is it possible, buying stm32 version, convert to daplink burning this firmware? Overall , can you provide addresses where where store bootloader and interface?

**Comment by FT9R** [comment]
If the PCB's are the same, it is possible to turn st-link to daplink and vice versa.
For daplink bootloader is located at `0x08000000` and interface at `0x0800C000`.
But more convienent way is to burn bootloader, pull reset down to ground and plug probe to usb.
MAINTENANCE drive will appear. Just drop interface to it

**Comment by TilBlechschmidt** [comment]
I just encountered the same situation and had problems flashing the files using my generic J-Link. Got it working in the end, here are the steps in case they are helpful to anyone else 🙂 

```bash
# 1. Attach the J-Link to the MiniDebugger 
# (As shown in the second README.md picture)

# 2. Start an OpenOCD session
$ openocd -c 'interface jlink; transport select swd' \
  -c 'source [find target/stm32f1x.cfg]' \
  -c 'init' \
  -c 'reset halt'

# 3. Connect to OpenOCD in another terminal
# (All commands below this one are run inside the OpenOCD telnet session!)
$ telnet localhost 4444

# 4. Unlock the STM32 
# (Mine was locked for some reason)
> stm32f1x unlock 0

# 5. Soft-reboot the chip
> reset init

# 6. Write the bootloader
> flash write_image erase stm32f103xb_bl_crc.bin 0x08000000

# 7. Write the firmware
> flash write_image erase 0257_stm32f103xb__0x0000.bin 0x0800C000

# 8. Reset for good measure
> reset init

# 9. Disconnect both your J-Link and the MiniDebugger

# 10. Reattach the MiniDebugger & profit! (MAINTENANCE USB drive should show up now)
```

I could not make it work using the `.hex` files provided in this repository, so I downloaded the [official DAPLink release](https://github.com/ARMmbed/DAPLink/releases/tag/v0257). Specifically, the `bootloaders` and `0257_release_package_gcc`. I am not sure why there are multiple toolchain folders inside the bootloaders archive, I picked the binary inside the `gcc` folder 🤷
